wordnik/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'market.views.index'),
    url(r'^search','market.views.search'),
    url(r'^company/all','market.views.allCompanies'),
    url(r'^company/(?P<co_id>\d+)/$', 'market.views.companyDetail'),
    url(r'^company/add','market.views.addCompany'),
    url(r'^company/edit/(?P<co_id>\d+)/$','market.views.editCompany'),
    url(r'^source/(?P<source_id>\d+)/$', 'market.views.sourceDetail'),
    #url(r'^source/delete/(?P<source_id>\d+)/$','market.views.sourceDelete'),
    #url(r'^source/admin','market.views.sourceAdmin'),
    url(r'^source/add','market.views.addSource'),
    url(r'^source/all','market.views.allSources'),
    #url(r'^metric/(?P<metric_id>\d+)/$','market.views.metricDetail'),
    url(r'^metric/add','market.views.addMetric'),
    url(r'^segment/all','market.views.allSegments'),
    url(r'^segment/(?P<seg_id>\d+)/$', 'market.views.segmentDetail'),
    url(r'^segment/add','market.views.addSegment'),
    url(r'^segment/edit/(?P<seg_id>\d+)/$', 'market.views.editSegment'),
    url(r'^tag/(?P<tag_id>\d+)/$', 'market.views.tagDetail'),
    url(r'^tag/all', 'market.views.tagAll'),
    url(r'^analysis/(?P<analysis_id>\d+)/$', 'market.views.analysisDetail'),
    url(r'^analysis/all', 'market.views.analysisAll'),
    url(r'^analysis/add/$', 'market.views.analysisAdd'),
    url(r'^analysis/addStream', 'market.views.analysisStreamAdd'),
    url(r'^login','market.views.login'),
    url(r'^logout','market.views.logout_view'),
    # url(r'^wordnik/', include('wordnik.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
)

urlpatterns += staticfiles_urlpatterns()

wordnik/market/models.py
from django.db import models
from django.contrib.auth.models import User

import datetime

PLATFORM_CHOICES = (
	('web','web'),
	('mobile','mobile'),
	('tablet','tablet'),
	('webmob','web, mobile'),
	('mobtab','mobile, tablet'),
	('webmobtab','web, mobile, tablet'),
)

STATE_CHOICES = (
	('active','active'),
	('inactive','inactive'),
	('alpha','alpha'),
	('beta','beta'),
)

EXIT_CHOICES = (
	('acq','acquisition'),
	('mgr','merger'),
	('bkrpt','bankruptcy'),
	('in','inactive'),
)

COMMENT_CHOICES = (
	('co','company'),
	('prod','product'),
	('met','metric'),
	('fea','feature'),
	('exit','exit'),
)

REGION_CHOICES = (
	('usa', 'United States'),
	('worldwide', 'Worldwide'),
)

class Comment(models.Model):
	user = models.ForeignKey(User)
	body = models.TextField()
	company = models.ForeignKey("Company",blank=True,null=True)
	category = models.CharField(max_length=20,choices=COMMENT_CHOICES)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	def was_published_today(self):
		return self.created.date() == datetime.date.today()
	
	def was_modified_today(self):
		return self.modified.date() == datetime.date.today()
	
# exit events for companies
class Exit(models.Model):
	type = models.CharField(max_length=450,choices=EXIT_CHOICES)
	amount = models.DecimalField(max_digits=24, decimal_places=2,blank=True,null=True)
	company = models.ForeignKey("Company",blank=True,null=True,related_name="company")
	acquirer = models.ForeignKey("Company",blank=True,null=True,related_name="acquirer")
	date = models.DateField(blank=True,null=True)
	modified = models.DateTimeField(auto_now=True)

# tags, used on pretty much all types of entities
class Tag(models.Model):
	name = models.CharField(max_length=450)
	description = models.TextField(null=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.name

# different market segments
class Segment(models.Model):
	name = models.CharField(max_length=250)
	description = models.TextField(blank=True,null=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.name

# pretty much the base model for linking all the other information together
# need to add logo
class Company(models.Model):
	name = models.CharField(max_length=250)
	parent = models.ForeignKey('self',blank=True,null=True,related_name="parent_comp")
	description = models.TextField(blank=True, null=True)
	slogan = models.TextField(blank=True)
	logo = models.FileField(upload_to='logos',blank=True)
	url = models.URLField(max_length=250,blank=True)
	platform = models.CharField(max_length=45,default="web",blank=True)
	ecosystem = models.ManyToManyField("Ecosystem",blank=True,null=True)
	segments = models.ManyToManyField(Segment,blank=True)
	#comments = models.ManyToManyField(Comment,blank=True,null=True)
	tags = models.ManyToManyField(Tag,blank=True)
	#exit = models.ForeignKey(Exit,blank=True,null=True)
	state = models.CharField(max_length=45,default="active",choices=STATE_CHOICES)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	public = models.IntegerField(default=0)
	ticker = models.CharField(max_length=45,blank=True,null=True)
	
	class Meta:
		verbose_name_plural = 'Companies'
	
	def __unicode__(self):
		return self.name

# specific company products	
class Product(models.Model):
	name = models.CharField(max_length=450)
	description = models.TextField(blank=True,null=True)
	value_prop = models.CharField(max_length=450)
	state = models.CharField(max_length=45,choices=STATE_CHOICES)
	features = models.ManyToManyField("Feature",through="ProductFeature")
	#comments = models.ManyToManyField(Comment,blank=True,null=True)
	tags = models.ManyToManyField(Tag)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.name

# generic feature type	
class Feature(models.Model):
	gen_name = models.CharField(max_length=450)
	gen_descr = models.TextField()
	gen_modified = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.gen_name

# product-specific features
class ProductFeature(models.Model):
	product = models.ForeignKey(Product)
	feature = models.ForeignKey(Feature)
	spec_name = models.CharField(max_length=250)
	spec_descr = models.TextField()
	tags = models.ManyToManyField(Tag,blank=True,null=True)
	#comments = models.ManyToManyField(Comment,blank=True,null=True)
	spec_modified = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.spec_name

class Source(models.Model):
	author = models.CharField(max_length=450,blank=True,null=True)
	source = models.CharField(max_length=450,blank=True,null=True)
	url = models.URLField(blank=True,null=True)
	file = models.FileField(upload_to='sources',blank=True,null=True)
	title = models.CharField(max_length=450)
	date = models.DateField(blank=True,null=True)
	tags = models.ManyToManyField(Tag,blank=True,null=True)
	#comments = models.ManyToManyField(Comment,blank=True,null=True)
	insight = models.TextField(blank=True,null=True)
	company = models.ManyToManyField(Company,blank=True, null=True)
	modified = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		if len(self.title) > 65:
			return self.title[:65] + " ..."
		else:
			return self.title
	
class Ecosystem(models.Model):
	name = models.CharField(max_length=450)
	description = models.TextField(blank=True,null=True)
	modified = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.name

class MetricType(models.Model):
	name = models.CharField(max_length=450)
	
	def __unicode__(self):
		return self.name

class Metric(models.Model):
	category = models.ForeignKey(MetricType)
	platform = models.CharField(max_length=25,blank=True)
	product = models.ForeignKey(Product,blank=True,null=True)
	region = models.CharField(max_length=45,choices=REGION_CHOICES,blank=True)
	company = models.ForeignKey(Company)
	round = models.CharField(max_length=45,blank=True,null=True)
	stat = models.CharField(max_length=25)
	date = models.DateField(blank=True,null=True)
	source = models.ForeignKey(Source,blank=True,null=True)
	
class BusinessModel(models.Model):
	name = models.CharField(max_length=250)
	description = models.TextField(blank=True,null=True)
	comments = models.ManyToManyField(Comment,blank=True,null=True)
	companies = models.ManyToManyField(Company,blank=True,null=True,through="BusinessModelDetails") 
	
	def __unicode__(self):
		return self.name
		
class BusinessModelDetails(models.Model):
	model = models.ForeignKey(BusinessModel)
	company = models.ForeignKey(Company)
	details = models.TextField()
	
class AnalysisStream(models.Model):
	name = models.CharField(max_length=450)
	description = models.TextField()
	tags = models.ManyToManyField(Tag,blank=True)
	companies = models.ManyToManyField(Company,blank=True)
	segments = models.ManyToManyField(Segment,blank=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

class Analysis(models.Model):
	title = models.CharField(max_length=250)
	description = models.TextField()
	file = models.FileField(upload_to='reports',blank=True)
	stream = models.ForeignKey(AnalysisStream)
	version = models.CharField(max_length=15)
	author = models.ForeignKey(User)
	created = models.DateTimeField(auto_now_add=True)
	

wordnik/market/forms.py
from django import forms
from django.forms.widgets import HiddenInput, Textarea
from django.contrib.auth.models import User
from market.models import Company, MetricType, Source, Segment, Ecosystem, AnalysisStream

SOURCE_TYPE_CHOICES = [
	('general','general'),
	('specific','specific')
	]

STATE_CHOICES = (
	('active','active'),
	('inactive','inactive'),
	('alpha','alpha'),
	('beta','beta'),
)

COMMENT_TYPE_CHOICES = (
	('co','company'),
	('prod','product'),
	('met','metric'),
	('fea','feature'),
	('exit','exit'),
)

ROUND_CHOICES = (
	('A','A'),
	('B','B'),
	('C','C'),
	('D','D'),
	('E','E'),
	('F','F'),
	('G','G'),
	('Un','Unattributed')
)

REGION_CHOICES = (
	('usa', 'United States'),
	('worldwide', 'Worldwide'),
)

PUBLIC_CHOICES = (
	(0,'No'),
	(1,'Yes'),
)

USERS = User.objects.all()

COMPANIES = Company.objects.all().order_by('name')

METRIC_TYPES = MetricType.objects.all().order_by('name')

SOURCES = Source.objects.all().order_by('title')

SEGMENTS = Segment.objects.all().order_by('name')

ECO = Ecosystem.objects.all().order_by('name')

ANALYSIS_STREAMS = AnalysisStream.objects.all().order_by('-created')

class CompanyForm(forms.Form):
	name = forms.CharField(max_length=250)
	description = forms.CharField(widget=forms.Textarea)
	public = forms.ChoiceField(choices=PUBLIC_CHOICES)
	stock_symbol = forms.CharField(required=False)
	#slogan = forms.CharField(required=False)
	logo = forms.FileField(required=False)
	url = forms.URLField()
	platform = forms.CharField()
	ecosystem = forms.ModelMultipleChoiceField(queryset=ECO,required=False)
	segments = forms.ModelMultipleChoiceField(queryset=SEGMENTS)
	tags = forms.CharField(required=False)
	state = forms.ChoiceField(choices=STATE_CHOICES)

class CompanyEditForm(forms.Form):
	id = forms.IntegerField(widget=HiddenInput)
	name = forms.CharField(max_length=250)
	description = forms.CharField(widget=forms.Textarea)
	public = forms.ChoiceField(choices=PUBLIC_CHOICES)
	#slogan = forms.CharField(required=False)
	logo = forms.FileField(required=False)
	url = forms.URLField()
	platform = forms.CharField(required=False)
	ecosystem = forms.ModelMultipleChoiceField(queryset=ECO,required=False)
	segments = forms.ModelMultipleChoiceField(queryset=SEGMENTS)
	tags = forms.CharField(required=False)
	state = forms.ChoiceField(required=True,choices=STATE_CHOICES)

class SourceForm(forms.Form):
	author = forms.CharField(required=False)
	source = forms.CharField()
	title = forms.CharField()
	date = forms.DateField(required=False)
	file = forms.FileField(required=False)
	url = forms.URLField(label="URL")
	#type = forms.ChoiceField(choices=SOURCE_TYPE_CHOICES)
	companies = forms.ModelMultipleChoiceField(queryset=COMPANIES,required=False)
	tags = forms.CharField(required=False)
	insight = forms.CharField(required=False,widget=forms.Textarea)
	
class MetricForm(forms.Form):
	company = forms.ModelChoiceField(queryset=COMPANIES,empty_label="Choose a company")
	platform = forms.CharField(max_length=25)
	category = forms.ModelChoiceField(queryset=METRIC_TYPES,empty_label="Choose a metric type")
	region = forms.ChoiceField(choices=REGION_CHOICES,required=False)
	stat = forms.CharField(max_length=25)
	round = forms.ChoiceField(choices=ROUND_CHOICES,required=False)
	date = forms.DateField()
	source = forms.ModelChoiceField(queryset=SOURCES,empty_label="Choose a source",required=False)

class SegmentForm(forms.Form):
	name = forms.CharField()
	description = forms.CharField(widget=forms.Textarea)

class CompanyCommentForm(forms.Form):
	user = forms.ModelChoiceField(queryset=USERS,widget=HiddenInput)
	category = forms.ChoiceField(choices=COMMENT_TYPE_CHOICES,widget=HiddenInput)
	company = forms.ModelChoiceField(queryset=COMPANIES,widget=HiddenInput)
	body = forms.CharField(widget=forms.Textarea)

class AnalysisStreamAddForm(forms.Form):
	name = forms.CharField()
	description = forms.CharField(widget=forms.Textarea)
	file = forms.FileField()
	author = forms.ModelChoiceField(queryset=USERS)
	tags = forms.CharField()
	companies = forms.ModelMultipleChoiceField(queryset=COMPANIES,required=False)
	segments = forms.ModelMultipleChoiceField(queryset=SEGMENTS,required=False)
	
class AnalysisAddForm(forms.Form):
	stream = forms.ModelChoiceField(queryset=ANALYSIS_STREAMS,widget=HiddenInput)
	title = forms.CharField()
	description = forms.CharField(widget=forms.Textarea)
	file = forms.FileField()
	version = forms.CharField()
	author = forms.ModelChoiceField(queryset=USERS)

wordnik/templates/market/analysis/add.html
{% extends "base.html" %}
{% block extrascripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/ckeditor/adapters/jquery.js"></script>
    <script type="text/javascript">
    	$(function() {
			$( 'textarea' ).ckeditor();
			
		});
    </script>
{% endblock %}

{% block sidebar %}



{% endblock %}

{% block pagetitle %}

{% endblock %}

{% block content %}
<p class="pageSubHead">Add a New Analysis</p>
<form action="/analysis/add/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	{% for field in form %}
        <p class="fieldWrapper">
            <span class="fieldLabel">{{ field.label_tag }}:</span>
        </p>
         <p class="fieldWrapper">
            {{ field.errors }}
			{{ field }}
        </p>
    {% endfor %}
	<input type="submit" value="Submit" />
</form>

{% endblock %}

wordnik/templates/market/analysis/addStream.html
{% extends "base.html" %}
{% block extrascripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/ckeditor/adapters/jquery.js"></script>
    <script type="text/javascript">
    	$(function() {
			$( 'textarea' ).ckeditor();
			
		});
    </script>
{% endblock %}

{% block sidebar %}



{% endblock %}

{% block pagetitle %}

{% endblock %}

{% block content %}
<p class="pageSubHead">Add a New Analysis</p>
<form action="/analysis/addStream/" method="post" enctype="multipart/form-data">
{% csrf_token %}
	{% for field in form %}
        <p class="fieldWrapper">
            <span class="fieldLabel">{{ field.label_tag }}:</span>
        </p>
         <p class="fieldWrapper">
            {{ field.errors }}
			{{ field }}
        </p>
    {% endfor %}
	<input type="submit" value="Submit" />
</form>

{% endblock %}

wordnik/templates/market/analysis/all.html
{% extends "base.html" %}

{% block sidebar %}



{% endblock %}

{% block pagetitle %}
All Reports
{% endblock %}

{% block content %}
{% if reps %}
	<ul class="slickList">
		{% for r in reps.object_list %}
			<li><a href="/rep/{{ r.id }}/">{{ r.name }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No reports in the database.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if reps.has_previous %}
            <a href="?page={{ reps.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ reps.number }} of {{ reps.paginator.num_pages }}.
        </span>

        {% if reps.has_next %}
            <a href="?page={{ reps.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}
	

wordnik/templates/market/analysis/streamDetail.html
{% extends "base.html" %}
{% block extrascripts %}

    
{% endblock %}

{% block sidebar %}
	

{% endblock %}

{% block pagetitle %}
	<div class="pageTitleBarDiv" id="coName">{{stream.name}}</div>
	
{% endblock %}

{% block content %}
	{{ stream.description|safe }}
	
	<ul class="slickList">
	{% for a in stream.analysis_set.all %}
		<li class="slickListItem">V.{{a.version}} <a href="{{a.file}}">{{ a.title }}</a></li>
	{% endfor %}
	</ul>
	
	{% if stream.segments %}
		<p class="pageSubHead">Market Segments</p>
		<ul class="slickList">
			{% for s in stream.segments.all %}
				<li class="slickListItem"><a href="/segment/{{ s.id }}">{{s.name}}</a></li>
			{% endfor %}
		</ul>
	{% endif %}
	
	{% if stream.tags %}
		<p class="pageSubHead">Tags</p>
		<ul class="slickList">
			{% for t in stream.tags.all %}
				<li class="slickListItem"><a href="/tag/{{ t.id }}">{{t.name}}</a></li>
			{% endfor %}
		</ul>
	{% endif %}
	
	{% if stream.companies %}
		<p class="pageSubHead">Related Companies</p>
		<ul class="slickList">
			{% for c in stream.companies.all %}
				<li class="slickListItem"><a href="/company/{{ c.id }}">{{c.name}}</a></li>
			{% endfor %}
		</ul>
	{% endif %}
	
	{% if stream.report_set %}
		<p class="pageSubHead">Reports</p>
		<ul class="slickList">
			{% for c in stream.report_set.all %}
				<li class="slickListItem"><a href="{{ r.file }}">{{r.title}}</a>, {{ r.author.name }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	
	
	

{% endblock %}